import type { NarrativeApiResponse, NarrativeToken } from "./types";

const now = Date.now();

function token(
  partial: Partial<NarrativeToken> & Pick<NarrativeToken, "id" | "name" | "symbol">,
): NarrativeToken {
  return {
    chainId: "solana",
    dexId: "pumpfun",
    address: partial.id,
    pairAddress: `pair-${partial.id}`,
    description: "",
    imageUrl: null,
    url: "https://dexscreener.com",
    priceUsd: 0.000042,
    marketCap: 42000,
    liquidityUsd: 12500,
    volume24h: 28500,
    priceChange24h: 84,
    buys24h: 311,
    sells24h: 184,
    pairCreatedAt: now - 1000 * 60 * 60 * 9,
    ageHours: 9,
    activeBoosts: 0,
    boostAmount: 0,
    hasAd: false,
    paidPromotion: false,
    websites: [],
    socials: [],
    ...partial,
  };
}

export const demoResponse: NarrativeApiResponse = {
  source: "demo",
  updatedAt: new Date().toISOString(),
  refreshSeconds: 30,
  tokenCount: 12,
  narrativeCount: 6,
  promotedTokenCount: 3,
  warning: "Live DEX data was unavailable, so NarrativeOS loaded demo signals.",
  narratives: [
    {
      id: "ai-animals",
      name: "AI Animals",
      category: "Animals",
      icon: "🐾",
      score: 94,
      status: "Exploding",
      growth24h: 187,
      volume24h: 248000,
      liquidityUsd: 92000,
      marketCap: 710000,
      transactions24h: 3890,
      tokenCount: 3,
      chainCount: 1,
      dexCount: 2,
      saturation: "Low",
      confidence: "High",
      promotedTokenCount: 1,
      description:
        "AI-generated animal characters are accelerating across new token launches and remix communities.",
      keywords: ["ai", "animals", "characters"],
      chains: ["solana"],
      tokens: [
        token({ id: "pixel-panda", name: "Pixel Panda AI", symbol: "PANDA", priceChange24h: 214, volume24h: 116000, marketCap: 310000 }),
        token({ id: "robot-raccoon", name: "Robot Raccoon", symbol: "RACC", priceChange24h: 178, volume24h: 79000, marketCap: 225000, activeBoosts: 20, boostAmount: 20, paidPromotion: true }),
        token({ id: "neural-cat", name: "Neural Cat", symbol: "NCAT", priceChange24h: 169, volume24h: 53000, marketCap: 175000 }),
      ],
    },
    {
      id: "ducks",
      name: "Ducks With Jobs",
      category: "Animals",
      icon: "🦆",
      score: 87,
      status: "Exploding",
      growth24h: 121,
      volume24h: 155000,
      liquidityUsd: 61000,
      marketCap: 480000,
      transactions24h: 2410,
      tokenCount: 2,
      chainCount: 1,
      dexCount: 1,
      saturation: "Very low",
      confidence: "High",
      promotedTokenCount: 0,
      description:
        "Ducks portrayed as accountants, delivery drivers, and office managers are gaining launch velocity.",
      keywords: ["ducks", "jobs", "office"],
      chains: ["solana"],
      tokens: [
        token({ id: "accountant-duck", name: "Accountant Duck", symbol: "QUACK", priceChange24h: 132, volume24h: 97000 }),
        token({ id: "working-duck", name: "Working Duck", symbol: "WORK", priceChange24h: 110, volume24h: 58000 }),
      ],
    },
    {
      id: "retro-internet",
      name: "Retro Internet",
      category: "Culture",
      icon: "💾",
      score: 82,
      status: "Exploding",
      growth24h: 96,
      volume24h: 181000,
      liquidityUsd: 74500,
      marketCap: 650000,
      transactions24h: 1980,
      tokenCount: 2,
      chainCount: 2,
      dexCount: 2,
      saturation: "Low",
      confidence: "High",
      promotedTokenCount: 1,
      description:
        "Pixel graphics, dial-up nostalgia, and early-web characters are appearing in multiple launch clusters.",
      keywords: ["retro", "pixel", "internet"],
      chains: ["solana", "base"],
      tokens: [
        token({ id: "dialup", name: "Dial Up", symbol: "56K", priceChange24h: 105, volume24h: 104000 }),
        token({ id: "cursor", name: "Pixel Cursor", symbol: "CURSOR", chainId: "base", priceChange24h: 87, volume24h: 77000, hasAd: true, paidPromotion: true }),
      ],
    },
    {
      id: "capybaras",
      name: "Capybara Wave",
      category: "Animals",
      icon: "🦫",
      score: 74,
      status: "Emerging",
      growth24h: 73,
      volume24h: 99000,
      liquidityUsd: 43200,
      marketCap: 315000,
      transactions24h: 1420,
      tokenCount: 2,
      chainCount: 1,
      dexCount: 1,
      saturation: "Very low",
      confidence: "Medium",
      promotedTokenCount: 0,
      description:
        "Relaxed capybara characters are returning through wholesome and absurd community remixes.",
      keywords: ["capybara", "animals", "wholesome"],
      chains: ["solana"],
      tokens: [
        token({ id: "capy-king", name: "Capy King", symbol: "CAPY", priceChange24h: 81, volume24h: 61000 }),
        token({ id: "capy-office", name: "Office Capy", symbol: "OCAPY", priceChange24h: 65, volume24h: 38000 }),
      ],
    },
    {
      id: "gaming-worlds",
      name: "Gaming Worlds",
      category: "Gaming",
      icon: "🎮",
      score: 67,
      status: "Emerging",
      growth24h: 48,
      volume24h: 72000,
      liquidityUsd: 36800,
      marketCap: 220000,
      transactions24h: 960,
      tokenCount: 2,
      chainCount: 2,
      dexCount: 2,
      saturation: "Low",
      confidence: "Medium",
      promotedTokenCount: 1,
      description:
        "Game-inspired mascots and nostalgic virtual worlds are forming a smaller but growing cluster.",
      keywords: ["gaming", "pixel", "worlds"],
      chains: ["solana", "base"],
      tokens: [
        token({ id: "loot-slime", name: "Loot Slime", symbol: "SLIME", priceChange24h: 54, volume24h: 44000 }),
        token({ id: "npc-coin", name: "NPC World", symbol: "NPC", chainId: "base", priceChange24h: 42, volume24h: 28000, activeBoosts: 10, boostAmount: 10, paidPromotion: true }),
      ],
    },
    {
      id: "food-memes",
      name: "Food Characters",
      category: "Food",
      icon: "🍜",
      score: 56,
      status: "Rising",
      growth24h: 29,
      volume24h: 44000,
      liquidityUsd: 27000,
      marketCap: 160000,
      transactions24h: 670,
      tokenCount: 1,
      chainCount: 1,
      dexCount: 1,
      saturation: "Very low",
      confidence: "Low",
      promotedTokenCount: 0,
      description:
        "Anthropomorphic food characters are showing early activity but need more token diversity for confirmation.",
      keywords: ["food", "characters"],
      chains: ["solana"],
      tokens: [token({ id: "ramen-boss", name: "Ramen Boss", symbol: "RAMEN", priceChange24h: 29, volume24h: 44000 })],
    },
  ],
};
